name: Docker Build

on:
  workflow_dispatch:

  push:
    branches: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build and run frontend
        run: cd frontend && npm ci && npm start && npm test
      - name: Build and run backend
        run: cd backend && npm ci && npm start && npm test
      - name: Build and run e2e test
        run: cd .. && npm ci && npm run test
