name: Build and test

on:
  workflow_dispatch:

  push:
    branches: main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build and test frontend
        run: |
          cd frontend 
          npm ci
          npm test
      - name: Build and test backend
        run: |
          cd backend
          npm ci
          npm test
