name: Docker Build

on:
  workflow_dispatch:

  push:
    branches: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          submodules: recursive
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
